version: '3'

services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER='-'
      - POSTGRES_PASSWORD='-'
      - POSTGRES_DB='-'
    ports:
      - "5432:5432"

  web_service:
    restart: always
    container_name: web_service
    build: .
    command: sh -c "cd rest_api_storage && gunicorn rest_api_storage.wsgi --bind 0.0.0.0:8000"
    environment:
      - POSTGRES_USER='-'
      - POSTGRES_PASSWORD='-'
      - POSTGRES_DB='-'
    depends_on:
      - db
    links:
      - db:db
    expose:
      - "8000"
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web_service
    volumes:
      - ./nginx:/etc/nginx/