version: '3'

services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER='-'
      - POSTGRES_PASSWORD='-'
      - POSTGRES_DB='-'
    ports:
      - "5432:5432"

  web_service:
    build: .
    environment:
      - POSTGRES_USER='-'
      - POSTGRES_PASSWORD='-'
      - POSTGRES_DB='-'
    command: gunicorn --bind 0.0.0.0:8000 rest_api_storage.wsgi
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
