version: '3'

services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER='-'
      - POSTGRES_PASSWORD='-'
      - POSTGRES_DB='-'
    ports:
      - "5432:5432"

  web_service:
    build: .
    environment:
      - POSTGRES_USER='-'
      - POSTGRES_PASSWORD='-'
      - POSTGRES_DB='-'
    command: ./bin/gunicorn_start.sh
    ports:
      - "8001:8001"
    depends_on:
      - db
    links:
      - db:db
