# Generated by Django 2.2.4 on 2019-09-02 07:22

import api_service_storage.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=api_service_storage.models.upload_image)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 9, 2, 7, 22, 24, 748867, tzinfo=utc))),
            ],
        ),
    ]
