# Generated by Django 2.2.4 on 2019-09-02 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_service_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
