# Generated by Django 2.2.4 on 2019-09-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service_storage', '0003_auto_20190904_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
    ]
