# Generated by Django 2.2.4 on 2019-09-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_service_storage', '0004_image_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='img',
        ),
    ]
